name: GitHub Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # dijalankan tiap hari
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: snake-outputs
          path: dist
